Integrate the first party YouTube client into Via
hypothesis/via pull request #1103
Opened 2023-07-19 19:27 UTC by jon-betts

2023-07-19 19:30 UTC, jon-betts commented on tests/unit/services.py
> -    return youtube_service
This violated the principal of least surprise for me. This is only required in one test, so I moved it there.

2023-07-19 19:31 UTC, jon-betts commented on tests/unit/via/views/view_video_test.py
> +        )
These tests are very intense. I really don't think we should be doing this anyway here which might reduce this effect

2023-07-19 19:31 UTC, jon-betts commented on via/views/view_video.py
> -    video_title = youtube_service.get_video_title(video_id)
I think part of the reason these tests aren't as nice as they could be is we have too many atomic calls.

The new method returns a single object with all these items inside it. It would be good to unify these.

2023-07-19 19:32 UTC, jon-betts commented on via/views/view_video.py
> +    video_title = youtube_service.get_video_title(video_id)
I moved these down, because we can early return if the video id isn't valid. Rather than doing lots of strange stuff.

2023-07-19 19:33 UTC, jon-betts commented on via/views/view_video.py
> +    video = youtube_service.get_video_info(video_url=url)
We could look this up in the parent, but I chose to keep it separate for now.

We could look to unify the look up with a call like:

```
youtube_service.get_video_info(video_url=url, get_captions=True)
```

Where we could use V3 stuff if `get_captions=False` or the V1 stuff if it's true etc.

2023-07-28 11:42 UTC, seanh commented
Labeling this as blocked just because it's waiting for me to get some more urgent PRs done before I can review this. I promise I'm working my way round to reviewing this ASAP!

2023-08-02 16:23 UTC, seanh requested changes
Not a proper review yet but just as a first-pass: I think the `video_url` argument to `get_video_info()` can be removed as it's unused, and the `via.video.lang` query param should be removed as nothing's going to be using it

2023-08-02 16:23 UTC, seanh commented on via/services/youtube.py
> +            video_id = self.get_video_id(video_url)
```suggestion
    def get_video_info(self, video_id) -> Video:
```

The `video_url` argument isn't needed: this is only called by `get_transcript()` below and it always passes `video_id` never `video_url`

2023-08-02 16:23 UTC, seanh commented on via/views/view_video.py
> +        return transcript_id
```suggestion
```

We should remove this as it'll be dead code: nothing is every going to be passing the `via.video.lang` param. We can add support for this query param back in a later PR when we need it

2023-08-15 11:41 UTC, seanh commented
Closing in favour of https://github.com/hypothesis/via/pull/1162

2023-08-15 11:41 UTC, closed without merging