Consider the resource type and referrer to get the URL to check
hypothesis/via pull request #278
Opened 2021-01-12 14:31 UTC by jon-betts

This attempts to distinguish between a page, resources in that page and other items to check what to run through checkmate.

We list the root pages, but not all sub-domains and CDNs where other content might be coming from. This means we need to be more lenient with sub-resources, but we should still check they come from somewhere trusted to the extent we can.

## Testing notes

 * To really test this you need checkmate actually enforcing the allow list
 * Checkout `allow-list` in checkmate and run `make services dev`
 * Run `make dev` here
 * Add some print statements in `blocker.py`?
 * Check some pages like: http://localhost:9080/https://www.theguardian.com/uk

2021-01-12 14:41 UTC, seanh commented on via/blocker.py
> +    VIA_HOST = "localhost:9080"
There does seem to be an `APP_URL` envvar already set on QA and prod but it's not set in dev and doesn't seem to be read anywhere in the code. But we can use that! (And just add it to `tox.ini` in dev.)

There may be some environment-based way to get it without setting our own envvar but :man_shrugging:

2021-01-12 20:00 UTC, jon-betts commented on requirements/format.txt
> +dataclasses==0.8          # via black
I did a `make requirements` and this came along for the ride

2021-01-12 20:01 UTC, jon-betts commented on tests/blocker_test.py
> +    EFFECTIVE_URL = "http://example.com/referrer"
I'm using all these prepared values because it's absolutely eye boggling trying to read the intent in the parameterisation without them as all the URLs look nearly the same.

2021-01-12 20:01 UTC, jon-betts commented on tests/blocker_test.py
> -        blocker._checkmate.check_url.assert_called_once_with(expected_url)
This is hefty covered above

2021-01-12 20:02 UTC, jon-betts commented on via/blocker.py
> +        for classified_url, allow_all in ((full_check, False), (partial_check, True)):
Without the caching above this could result in a lot of repetitious tests. In truth it still will as the calls will be distributed across different instances, but at least we have a fighting chance.

2021-01-12 20:04 UTC, jon-betts commented on via/blocker.py
> +            domain_to_annotate=classified_url.parsed.netloc,
This is effectively how it was before, but I think this is actually a bug. This is the parsed URL from the original raw URL. This will _mostly_ be right, but in the case where the URL didn't have a scheme, `urlparse` will have made a mess of it.

We correct for this with `clean_url`, but we probably should re-parse the `effective_url` here to get the right domain.

2021-01-12 20:06 UTC, jon-betts commented on via/blocker.py
> +    VIA_HOST = "localhost:9080"
Rob was right, we can get it from `HTTP_HOST` I think.

2021-01-12 20:08 UTC, jon-betts commented on tests/blocker_test.py
> +    def good_urls(self, CheckmateClient):
This is applied in a plural context now for the main url and referrer

2021-01-13 13:43 UTC, seanh requested changes
I think we should scoop out the caching into a separate optimisation PR.

I've got an optional suggestion to remove an unnecessary Checkmate check in one case.

Various refactoring small and big (and some more vague suggestions), I think they can all be optional.

2021-01-13 13:43 UTC, seanh commented on tests/blocker_test.py
> +            ),
Can we change the super-terse comments style on these? I found it hard to figure out what the comments meant. E.g. instead of `# * -> via_landing_page == landing_page` maybe just say `# No checks are done for the Via landing page, regardless of what the Referer header is.`.

I think it might be better _not_ to collapse `referrer` and `path` into `urls` and `full_check` and `partial_check` into `checks`. It means I have to scroll up to the top of the `@pytest.mark.parametrize()` to see what the parametrized arguments are (`"urls,checks"`) and then scroll down to the test body to see what they _actually_ are (`referrer, path = urls` and `full_check, partial_check = checks`). This made it a fair bit harder for me to understand this. Especially since one of the "urls" is actually a path.

Just expand them into a 4-tuple instead of two 2-tuples:

```python
@pytest.mark.parametrize("referer,path,full_check,partial_check", [
    (
        # No checks are done for the Via landing page, regardless of what the Referer header is.
        "http://irrelevant", Path.VIA_HOME_PAGE, None, None,
    ),
    ...
])
```

Or use dicts:

```python
@pytest.mark.parametrize("params", [
    (
        # No checks are done for the Via landing page, regardless of what the Referer header is.
        dict(
            referer="http://irrelevant",
            path=Path.VIA_HOME_PAGE,
            full_check=None,
            partial_check=None,
    ),
    ...
])
```

2021-01-13 13:52 UTC, jon-betts commented on tests/blocker_test.py
> +            ),
The collapsing here is done to aid readability, otherwise when you run black you end up with:

```python
(
  # comment
  line_1
  line_2
  line_3
  line_4
),
```
Dicts end up even worse as they add another couple of lines too, which means everything is very far from the definition.

I'll add on some more human friendly descriptions. These descriptions are here to directly tie the cases to the named cases in the function under test.
And it ends up extremely long

2021-01-13 14:20 UTC, jon-betts commented on tests/blocker_test.py
> +            ),
This isn't as bad with the constants as it was with the full strings. I've shortened the names a bit and had a go getting this on single lines.

2021-01-13 14:21 UTC, jon-betts commented on via/blocker.py
> +        return self.checker.check_url(url_to_check, allow_all=allow_all)
I've removed this now, we can have a think again later. With changes to the rules there is no big increase in repetitive calls.

2021-01-13 14:25 UTC, jon-betts commented on via/blocker.py
> +        # Parse the URL and referrer
I've renamed this "_get_urls_to_check" and expanded the readme.

2021-01-13 14:26 UTC, jon-betts commented on via/blocker.py
> +        for classified_url, allow_all in ((full_check, False), (partial_check, True)):
This is a refactoring boo boo. The above url wasn't called "classified_url" originally

2021-01-13 14:27 UTC, jon-betts commented on via/blocker.py
> +        url_type, ref_type = url.type, referrer.type
As the rules are so simple now, I've replaced these with literal references to "referrer.type" etc.

2021-01-13 14:27 UTC, jon-betts commented on via/blocker.py
> +            return referrer, url, "referrer_check"
This has been removed now

2021-01-13 14:46 UTC, jon-betts commented on via/blocker.py
> +class ClassifiedURL(object):
I think classes here are probably over kill. I've made this into a class which accepts arguments without mucking about with them too much, and a separate class method which does the classification and construction. I've also added your comments to the relevant lines.

I think this makes it clearer what's going on.

2021-01-13 14:47 UTC, jon-betts commented on via/blocker.py
> +            return None, None
It shouldn't, but in the event there simply isn't a "HTTP_REFERRER" we don't want to crash. This could happen with `curl` for example. This means our code will carry on, but we should just fall into a default case.

2021-01-13 14:56 UTC, jon-betts commented on via/blocker.py
> +        )
I didn't know about this, and it's certainly much shorter, but I'm not sure in general it's actually useful. Here's a more filled out example:

`ClassifiedURL(u'via_sub_resource', u'http:/...mple.com', u'http:/...mple.com', u'oe')`

So you can't really see the URLs there to any useful extent.

I'll switch to this for most of it, but I think the URLs just have to be in there as is. So this is a kind of half way house.

2021-01-13 15:04 UTC, jon-betts commented on via/blocker.py
> +            self.resource_type = None
I'm hoping this init method makes the relationships between the different values more clear

2021-01-13 15:15 UTC, jon-betts commented on via/blocker.py
> +            domain_to_annotate=classified_url.parsed.netloc,
This has been fixed now.

2021-01-13 16:05 UTC, seanh commented on via/blocker.py
> +        for classified_url, allow_all in ((full_check, False), (partial_check, True)):
I suspect PyLint would have caught this (I think I've seen it complain about this sort of thing before) but Via only uses Flake8

2021-01-13 16:24 UTC, seanh commented on via/blocker.py
> +        )
This isn't quite right because, while `type` and `resource_type` are being formatted correctly because they're passed to `repr()`, `raw_url` and `proxied_url` aren't formatted correctly (they're not wrapped in quotes), so you have a mix of quoted and non-quoted strings:

```python
>>> ClassifiedURL("test_type", "https://example.com", "https://via.hypothes.is/https://example.com", "test_resource_type")
ClassifiedURL('test_type', https://example.com, https://via.hypothes.is/https://example.com, None)
```

`repr()` will wrap strings in quotes, but _not_ wrap `None` in quotes, etc (generally it'll format the value correctly according to its type).

If you specifically want to override the default behaviour and _not_ shorten long URL strings then I think you have to set `maxstring`:

```python
from repr import Repr

def __repr__(self):
    repr = Repr()
    # Allow unicode strings and byte strings to be up to 99 chars long before shortening them.
    repr.maxstring = repr.maxother = 99

    return "%s(%s, %s, %s, %s)" % (
        self.__class__.__name__,
        repr.repr(self.type),
        repr.repr(self.raw_url),
        repr.repr(self.proxied_url),
        repr.repr(self.resource_type),
    )
```

Result:

```python
>>> ClassifiedURL("test_type", "https://example.com", "https://via.hypothes.is/https://example.com", "test_resource_type")
ClassifiedURL('test_type', 'https://example.com', u'https://via.hypothes.is/https://example.com', None)
```

2021-01-13 16:43 UTC, seanh commented on tests/blocker_test.py
> +            ),
I'd say dicts are the clear winner here, as each dict puts the param names right next to the values (on the other side of the `=`). It adds repetition of the param names, but there's no scrolling up and down to try to map the param names and their order to the tuples or to see what gets unpacked into what and in what order. It's much easier to read. The overall vertical height of the `parametrize()` doesn't seem like a readability issue to me, since each dict within it is self-explanatory, your eyes don't need to jump around between the top, middle and below the `parametrize()` to understand a given test case.

```python
@pytest.mark.parametrize("params", [
    # No checks are done for the Via landing page, regardless of what the Referer header is.
    dict(
        referer="http://irrelevant",
        path=Path.VIA_HOME_PAGE,
        full_check=None,
        partial_check=None,
    ),
    ...
])
def the_test(params):
    ...
```

2021-01-13 17:31 UTC, seanh approved these changes
Various refactoring and docstring suggestions

2021-01-13 17:31 UTC, seanh commented on via/blocker.py
> +            return ClassifiedURL(None, raw_url)
The comment is a little enigmatic. Is it really nonsense? For example I think this might happen whenever the referrer header is blocked.

```suggestion
        if not raw_url:
            # This happens when the Referer header is missing.
            return ClassifiedURL(None, raw_url)
```

2021-01-13 17:31 UTC, seanh commented on via/blocker.py
> +            return ClassifiedURL("3rd_party", raw_url)
This is a little confusing at first--how can the hostname of a request _to Via_ be the hostname of a site other than Via? But of course it's because we also construct `ClassifiedURL`'s for the referer URLs. I tweaked the comment 

```suggestion
        if not assume_via and parsed.netloc != via_host:
            # This happens when the URL in the Referer header is to a site other than Via.
            return ClassifiedURL("3rd_party", raw_url)
```

2021-01-13 17:31 UTC, seanh commented on via/blocker.py
> +            # A request to Via's landing page
```suggestion
            # A request to Via's landing page.
```

:+1:

2021-01-13 17:31 UTC, seanh commented on via/blocker.py
> +            # A request for a sub-resource of a proxied page.
:+1:

2021-01-13 17:31 UTC, seanh commented on via/blocker.py
> +            return ClassifiedURL(None, raw_url)
```suggestion
            return cls(None, raw_url)
```

It should either use `cls` or it should be a `staticmethod` not a `classmethod`. I've seen people say that, for factory methods, an `@classmethod` that uses `cls` is better because it avoids duplicating the class name. On the other hand an `@staticmethod` that uses `ClassifiedURL()` makes it easier to find all the places where `ClassifiedURL()` is called by grepping for it -- duplicating the class name may actually be a good thing, and deduplicating it may simply make the code harder to grep. (The reference to `cls.SUB_RESOURCE_RE` would also need to be changed.)

2021-01-13 17:31 UTC, seanh commented on via/blocker.py
> +class ClassifiedURL(object):
The `ClassifiedURL` class is much easier to understand now :+1:

It still doesn't have any documentation of its public interface (`raw_url`, `type`, `proxied_url`, `proxied_domain`, `resource_type`).

I still think it's a problem that I have to read the body of `classify()` to figure out what the 5 types of URL are (corresponding to the 5 values that `ClassifiedURL.type` can take: `None`, `"3rd_party"`, `"via_landing_page"`, `"via_sub_resource"` or `"via_page"`). A class isn't a heavy thing (it's just one line of code and a docstring, in the minimal case) and would make it easier to understand the code without having to read every line of it.

2021-01-13 17:31 UTC, seanh commented on via/blocker.py
> +        :return: A tuple of (full_check_url, partial_check_url, rule_type)
```suggestion
        :return: A tuple of (url_to_fully_check, url_to_partially_check, rule_type)
```

2021-01-13 17:31 UTC, seanh commented on via/blocker.py
> +        should get a partial allow list disabled check.
```suggestion
        Return a tuple of three items:
 
        1. A URL that should be "fully checked" (checked against both Checkmate's
           allow-list and its block-list).
           This will be one of the given `url` or `referrer`, or `None`
        2. A URL that should be "partially checked" (checked against Checkmate's
           block-list only).
           This will also be one of the given `url` or `referrer`, or `None`
        3. The name of the triggered rule (for debugging)
```

Making this a bit more explicit (particularly about what "fully checked" and "partially checked" mean, defining the terms)

2021-01-13 17:31 UTC, seanh commented on via/blocker.py
> +        The third item is the name of the triggered rule (purely for debugging)
```suggestion
```

2021-01-13 17:31 UTC, seanh commented on via/blocker.py
> +        return url, None, "page_to_check"
:+1: very clear

2021-01-13 17:39 UTC, jon-betts commented on via/blocker.py
> +class ClassifiedURL(object):
I can add some more doc-strings to this.

2021-01-13 17:41 UTC, jon-betts commented on via/blocker.py
> +        :param proxied_url: If this is a Via proxy, the proxied site
I can swap to `url_to_proxy`. The `raw_url` is not a Via URL has it could be a third party site entirely in the case of a referrer.

2021-01-13 17:42 UTC, jon-betts commented on via/blocker.py
> +            self.resource_type = None
No it's not expected, but it makes it clear what the situation is. I can put that in instead.

2021-01-13 17:55 UTC, jon-betts commented on via/blocker.py
> +    SUB_RESOURCE_RE = re.compile(r"^/([a-z]{2})_/(.*)$")
I've moved this down. It's common practice to keep constants at the top of files.

2021-01-13 17:59 UTC, jon-betts commented on via/blocker.py
> +            return ClassifiedURL(None, raw_url)
I've kept this as a class method and used `cls`

2021-01-13 18:59 UTC, merged