Add checkmate API key
hypothesis/via pull request #283
Opened 2021-02-03 08:40 UTC by marcospri

Missing updating tests and bumping checkmatelib version.

2021-02-11 17:02 UTC, seanh approved these changes

2021-02-12 11:17 UTC, seanh requested changes

2021-02-12 11:17 UTC, seanh commented on tox.ini
> +    dev: CHECKMATE_API_KEY = not_api_key
```suggestion
    dev: CHECKMATE_API_KEY = dev_api_key
```

It actually _is_ an API key :) It's just the one we use in dev

2021-02-12 11:48 UTC, marcospri commented on tox.ini
> +    dev: CHECKMATE_API_KEY = not_api_key
Updated it in all PRs

2021-02-16 17:42 UTC, seanh approved these changes

2021-02-17 10:02 UTC, merged